# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05model\":\n\x0cImageRequest\x12\x13\n\x0bimageBuffer\x18\x01 \x01(\x0c\x12\x15\n\rminConfidence\x18\x02 \x01(\x02\"\xc5\x01\n\tDetection\x12\x11\n\tclassName\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\r\n\x05x_min\x18\x03 \x01(\x02\x12\r\n\x05y_min\x18\x04 \x01(\x02\x12\r\n\x05x_max\x18\x05 \x01(\x02\x12\r\n\x05y_max\x18\x06 \x01(\x02\x12\x10\n\x08x_center\x18\x07 \x01(\x02\x12\x10\n\x08y_center\x18\x08 \x01(\x02\x12\r\n\x05width\x18\t \x01(\x02\x12\x0e\n\x06height\x18\n \x01(\x02\x12\x12\n\nnormalized\x18\x0b \x01(\x08\"D\n\tModelInfo\x12\x11\n\tmodelName\x18\x01 \x01(\t\x12\x14\n\x0cmodelVersion\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\"*\n\tImageInfo\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"g\n\x12PerformanceMetrics\x12\x14\n\x0cpreprocessMs\x18\x01 \x01(\x01\x12\x13\n\x0binferenceMs\x18\x02 \x01(\x01\x12\x15\n\rpostprocessMs\x18\x03 \x01(\x01\x12\x0f\n\x07totalMs\x18\x04 \x01(\x01\"\xab\x01\n\rModelResponse\x12#\n\tmodelInfo\x18\x01 \x01(\x0b\x32\x10.model.ModelInfo\x12#\n\timageInfo\x18\x02 \x01(\x0b\x32\x10.model.ImageInfo\x12*\n\x07metrics\x18\x03 \x01(\x0b\x32\x19.model.PerformanceMetrics\x12$\n\ndetections\x18\x04 \x03(\x0b\x32\x10.model.Detection2I\n\x0cModelService\x12\x39\n\x0cProcessImage\x12\x13.model.ImageRequest\x1a\x14.model.ModelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=22
  _globals['_IMAGEREQUEST']._serialized_end=80
  _globals['_DETECTION']._serialized_start=83
  _globals['_DETECTION']._serialized_end=280
  _globals['_MODELINFO']._serialized_start=282
  _globals['_MODELINFO']._serialized_end=350
  _globals['_IMAGEINFO']._serialized_start=352
  _globals['_IMAGEINFO']._serialized_end=394
  _globals['_PERFORMANCEMETRICS']._serialized_start=396
  _globals['_PERFORMANCEMETRICS']._serialized_end=499
  _globals['_MODELRESPONSE']._serialized_start=502
  _globals['_MODELRESPONSE']._serialized_end=673
  _globals['_MODELSERVICE']._serialized_start=675
  _globals['_MODELSERVICE']._serialized_end=748
# @@protoc_insertion_point(module_scope)
